### ISSUE TITLE
Fix documentation for `getTests`

### ISSUE THREAD

**Issue by danjm** [ethereumjs/ethereumjs-testing#32]
The current documentation for `getTests` is actually documentation for a method that existed on an old version but no longer exists: https://github.com/ethereumjs/ethereumjs-testing/blob/master/index.js#L9-L12

This documentation should be updated. This is a simple and straightforward task, I'm just making an issue so that it doesn't get forgotten.

**Comment by holgerd77** [comment]
Thanks!

**Comment by a1300** [comment]
Please assign this issue to me

**Comment by alcuadrado** [comment]
Thanks for collaborating @a1300! I've assigned this issue to you :)

**Comment by ryanio** [comment]
I believe this can be closed now since https://github.com/ethereumjs/ethereumjs-testing/commit/d661b2e933193621cb9617c8885ae155899429db added the right JSDoc for the `getTests` function. (It looked [like this](https://github.com/ethereumjs/ethereumjs-testing/blob/v1.2.5/index.js#L9-L12) when OP opened the issue.)

**Comment by holgerd77** [comment]
@ryanio Thanks for the hint and the comprehensible linking aligned, will close.
